#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SNMP-Interfaces
version:      1.1
version_from: lib/Net/SNMP/Interfaces.pm
installdirs:  site
requires:
    Net::SNMP:                     3.5
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
